### PR TITLE
Add xcaudit for test logs in GitHub action

### PR DESCRIPTION
**Pull request by Alexander-Ignition**

### CODE REVIEW

**Comment by subdan** [comment]
Could you please show how it looks like by temporary adding one warning and one error in the FigmaExport code.

**Comment by Alexander-Ignition** [comment]
@subdan  `xcaudit` highlights errors and warnings

you can view it in

- [Actions Summary](https://github.com/RedMadRobot/figma-export/actions/runs/678741234)
- [Pull Request / Checks / Build logs](https://github.com/RedMadRobot/figma-export/runs/2173027615?check_suite_focus=true)
- [Pull Request / Files Changed](https://github.com/RedMadRobot/figma-export/pull/88/files)

**Comment by Alexander-Ignition** [comment]
Oh I've seen a few flaws

- [ ] add  `shell: bash` to GitHub action to correctly handle test crashes
- [ ] check and fix duplicate warnings
- [ ] make highlighting of `fatalError` and other asserts

**Comment by Alexander-Ignition** [comment]
duplication of warnings is a compiler bug
https://bugs.swift.org/plugins/servlet/mobile#issue/SR-13640

**Comment by Alexander-Ignition** [comment]
@subdan  I updated xcuadit and failed-pr
https://github.com/RedMadRobot/figma-export/actions/runs/714571277

**Pull request closed without merging**
