### PR TITLE
Support exporting typography for Android

### PR DESCRIPTION
**Pull request by simonlee2**
## Description

Export typography styles into an XML file for Android. Each of the text styles is exported into the following format:

``` xml
<style name="body">
  <item name="android:fontFamily">@font/ptsans_regular</item>
  <item name="android:textSize">16.0sp</item>
</style>
```
- post-script names are processed into `@font/{lower_cased_post_script_name}`
- font size specifies `sp` to honor user's text preferences

### CODE REVIEW

**Comment by subdan** [comment]
Wow! Thanks! I will check it out by the end of the week.

Do you plan to add support for custom line height? Example:
```xml
<item name="lineHeight">20sp</item>
<item name="android:minHeight">20sp</item>

```

**Comment by simonlee2** [comment]
> Wow! Thanks! I will check it out by the end of the week.
> 
> Do you plan to add support for custom line height? Example:
> 
> ```
> <item name="lineHeight">20sp</item>
> <item name="android:minHeight">20sp</item>
> ```

Thanks for the quick response. figma-export has been helpful for our design system pipeline 🎉

We don't have plans on adding that soon as our team plans to set the line height separately for now.

**Review by subdan — CHANGES_REQUESTED** [review]
- Add information about this new feature to the README.md
- Update [Examples/README.md](https://github.com/RedMadRobot/figma-export/blob/master/Examples/README.md) by changing android screenshots.
- Add font files to the `res/font` directory of AndroidExample project
- Update AndroidExample project by adding a new tab “Typography” with four TextView

**Comment by subdan** [comment]
Change name of the font files.

Font files placed at `main/res/font` must contain only lowercase a-z, 0-9, or underscore.

image

**Comment by subdan** [comment]
Update AndroidExample project by adding a new tab “Typography” with four TextView

**Pull request merged**
