### PR TITLE
Fixed image and icons export for iOS with additional suffix

### PR DESCRIPTION
**Pull request by ne1true**
Fixed image export with suffix for dark mode
Fixed icons export with suffix for renderMode mode (dark mode suffix should be last)

### CODE REVIEW

**Comment by subdan** [comment]
Hello. Could you please explain in more detail which bug have you fixed?

**Comment by ne1true** [comment]
1. Fixed image export with suffix for dark mode.
In case you set 'useSingleFile' to true you will always get 'secondAssetsNotFoundInFirstPalette' error. This was because the '_dark' suffix is not removed from image name.
2. Fixed icons export with suffix for renderMode mode (dark mode suffix should be last)
In case you set 'renderModeDefaultSuffix', 'renderModeOriginalSuffix' or 'renderModeTemplateSuffix' you will always get 'renderMode' on icons in assets. This was because the 'renderMode' suffix is not removed from icon name before being renamed to camelCase or snakeCase.

**Review by subdan — APPROVED** [review]

**Comment by subdan** [comment]
I've just noticed that you call `updateRenderMode` in `loadIconsFromSingleFile` method only. You've forgotten to call `updateRenderMode` in `loadIconsFromLightAndDarkFile`.

**Comment by ne1true** [comment]
Sorry, I forgot about this function. Do I need to create new pr with that fix?

**Comment by ne1true** [comment]
You can also remove the renderMode fields from XcodeImagesOutput.

**Pull request merged**
