### PR TITLE
Add StencilSwiftKit

### PR DESCRIPTION
**Pull request by alexey1312**
### What did

- Up Stencil version to 0.15.1
- Added [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit/tree/402aaf406b6f0ad70effa2e055b2ea7541fbd100)

### Motivation

Add new nodes & filters dedicated to Swift code generation.

### CODE REVIEW

**Comment by subdan** [comment]
Why do we need `StencilSwiftKit`?

**Comment by alexey1312** [comment]
> Why do we need `StencilSwiftKit`?

StencilSwiftKit will add more flexibility in code generation.

**Comment by subdan** [comment]
- `StencilSwiftKit` adds 3 new dependencies that isn‘t good.
- Current templates written without `StencilSwiftKit`. Could you please show how `StencilSwiftKit` can simplify templates?

Do you plan to use `StencilSwiftKit` in FigmaExport?

**Comment by alexey1312** [comment]
Yes, we are using StencilSwiftKit now, from my branch.
We use custom template in the project. 
And we have several color assets whose names should be the same. Without filters like replace, lowerFirstWord and more this is impossible to implement...

P.S. It would be cool to add custom names for templates.

**Pull request merged**
